### ISSUE TITLE
Enhance Obvs.RabbitMQ to allow processing as a queue

### ISSUE THREAD

**Issue by Unthred** [inter8ection/Obvs.RabbitMQ#1]
If I have a subscriber service on 3 separate machines I would like the ability to have just one subscriber process a message which can then be removed from the queue instead of all 3 processing it.

**Comment by christopherread** [comment]
Hi, after discussion on Obvs Gitter channel, I am closing this until there is a more compelling use case. Currently Obvs is primarily designed for pub/sub over topics, which is a good fit for the Rx API.
