### ISSUE TITLE
Queue name contains the exchange name twice

### ISSUE THREAD

**Issue by Unthred** [inter8ection/Obvs.RabbitMQ#5]
creating a ServiceBus so 
                ServiceBus = Obvs.ServiceBus.Configure()
                .WithRabbitMQEndpoints<ISettingsBaseMessage>()
                .Named("private.ex.surveyor-TestName")
                .ConnectToBroker(_connectionString)
                .SerializedAsJson()
                .AsServer()
                .UsingLog4Net()
                .Create();
results in an exchange named so - private.ex.surveyor-TestName
and a queue named so - private.ex.surveyor-TestName.private.ex.surveyor-TestName.Commands-SO-SIMONM-simonm-34360-1*

So there is a duplication of the queue name

**Comment by christopherread** [comment]
This is because it is concatenating the routing key with the exchange name, but the routing key already contains the exchange name. Will fix.
