### ISSUE TITLE
Obvs.RabbitMQ 4.0.0.4 was restored using '.netframework version=v4.6.1' instead of the project target framework

### ISSUE THREAD

**Issue by csmorley** [inter8ection/Obvs.RabbitMQ#8]
Not sure if an issue (and not sure why doesn't pickup .net standard) but my .net core 2.0 app is throwing `Obvs.RabbitMQ 4.0.0.4 was restored using '.netframework version=v4.6.1' instead of the project target framework` NU1701 warning in the build output. Any ideas please?

**Comment by ankorus** [comment]
It looks like megakid's commit #7 https://github.com/christopherread/Obvs.RabbitMQ/commit/b00c7b2ea2f8648c7bd82e28fdb6881ceb2a9ff7 is merged yet not pushed to nuget. If this is the case, Chris, could you, please, push the obvs.RabbitMQ version supporting .net core to nuget. Thx in advance,

**Comment by christopherread** [comment]
Thanks for reminder, published latest build

**Comment by christopherread** [comment]
Resolved
